<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="">
  <eClassifiers xsi:type="ecore:EClass" name="Petri Nets">
    <eStructuralFeatures xsi:type="ecore:EReference" upperBound="-1" eType="#//Arc"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" upperBound="-1" eType="#//Node"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" upperBound="-1" eType="#//Arc"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" upperBound="-1" eType="#//Arc"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Arc">
    <eStructuralFeatures xsi:type="ecore:EReference" lowerBound="1" eType="#//Specification"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Place" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EReference" upperBound="-1" eType="#//Token"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="Token">
    <eStructuralFeatures xsi:type="ecore:EReference" lowerBound="1" eType="#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Specification">
    <eStructuralFeatures xsi:type="ecore:EReference" lowerBound="1" eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberofTokens" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
